### ISSUE TITLE
Implement server side code to exec all scripts and return pass or fail

### ISSUE THREAD

**Issue by piouson** [jgodstime/team-fury-1#1]
- [x] Run `exec` on all files in `./scripts` and read `results`
- [x] Compare each `result` with expected output
- [x] Output `pass` if `result` match expected or `fail` otherwise

> Example `JSON` output

```json
{
  "file": "myScript.py",
  "output": "Hello World, this is Olagesin Samuel with HNGi7 ID HNG-04817 using Python for stage 2 task",
  "name": "Olagesin Samuel",
  "id": "HNG-04817",
  "email": "seyi@hng.tech",
  "language": "Python",
  "status": "Pass"
}
```

> Example `HTML` output

```html
<table>
  <tr>
    <th>file</th>
    <th>output</th>
    <th>name</th>
    <th>id</th>
    <th>email</th>
    <th>language</th>
    <th>status</th>
  </tr>
  <tr>
    <td>myScript.py</td>
    <td>Hello World, this is Olagesin Samuel with HNGi7 ID HNG-04817 using Python for stage 2 task</td>
    <td>Olagesin Samuel</td>
    <td>HNG-04817</td>
    <td>seyi@hng.tech</td>
    <td>Python</td>
    <td>Pass</td>
  </tr>
</table>
```

**Comment by piouson** [comment]
No knowledge of PHP but good with regex, I've just read the PHP documentation and came up with this.

> Regex pattern for matching output

```php
$pattern = "/Hello\sWorld,\sthis\sis\s\w+(?:\s\w+)*\swith\sHNGi7\sID\sHNG-[0-9]{5}\susing\s\w+\sfor\sstage\s2\stask/";
```

> Read files in `scripts` folder using [`glob`](https://www.php.net/manual/en/function.glob.php)

```php
$files = glob('./scripts/*');
```

> Run [`exec`](https://www.php.net/manual/en/function.exec) on each file and compare with [`preg_match`](https://www.php.net/manual/en/function.preg-match)

```php
foreach($files as $file) {
  if (preg_match("/.py\b/", $file)) {
    $output = exec("python $file");
  }
  else if (preg_match("/.js\b/", $file)) {
    $output = exec("node $file");
  }
  else if (preg_match("/.php\b/", $file)) {
    $output = exec("php $file");
  }
  else {
    # handle other languages here
    $output = exec($file);
  }

  if (preg_match($pattern, $output)) {
    echo "Pass! = $file\r\n";
  }
  else {
    echo "Fail! = $file\r\n";
  }
}
```
> An idea for other languages might be to use [`get_file_contents`](https://www.php.net/manual/en/function.file-get-contents.php) and [`preg_match`](https://www.php.net/manual/en/function.preg-match)

**Comment by piouson** [comment]
[`$_SERVER`](https://www.php.net/manual/en/reserved.variables.server.php) might be useful to check that query string equals `json`, then show `json` output with [`json_encode()`](https://www.php.net/manual/en/function.json-encode)

```php
if $_SERVER['QUERY_STRING'] == "json"
  echo json_encode($output)
else
  echo $output

**Comment by delight500** [comment]
I have written a script that runs js and python but and prints the desired result but I can't get it to run PHP any help

**Comment by ghost** [comment]
> I have written a script that runs js and python but and prints the desired result but I can't get it to run PHP any help

we already have 2 scripts doing that, but let's see yours, we are trying to compare the results with a particular pattern

**Comment by piouson** [comment]
> I have written a script that runs js and python but and prints the desired result but I can't get it to run PHP any help

@delight500 please share your code here. If your environment runs php, you can just use `exec("php $file")` to run php file.. it should also work from the command line but you need to add php path to your system variables if using Windows

**Comment by samueluchendu** [comment]
weldone guys,  currently working on how to display all files in json format, i would share my code as soon as am done.

**Comment by piouson** [comment]
@geraldon1997 and everyone else, please share your written code here to compare and merge efforts

**Comment by Bisola248** [comment]
Well done guys, still working on my code as well but I'm using SQL

**Comment by thebolarin** [comment]
Weldone guys

**Comment by maroafenogho** [comment]
Great job guys.

**Comment by Emmyola** [comment]
Welcome guys, God will bless all our effort, keep moving is the key to archive our goal...working on my too using php

**Comment by Abuh05** [comment]
Weldone guys, Lets get to work. Just coming now

**Comment by simply-alliv** [comment]
Firstly, where are we going to host the backend (server side) code? Have we sorted that out yet?

Secondly, do we need to make an API for the frontend developers?

**Comment by piouson** [comment]
@simply-alliv yea an API is the best outcome, this way the frontend team maintain their code and link the backend work in `index.html`

**Comment by sheuabdulazeez** [comment]
- This runs  exec on the .py, .js and .php 

- It compare the message with the format  given and assign fails and passes

- It displays the json format when ?json added

- This takes in json object with the requires



```
<?php
$dir = "./scripts/";
$files = scandir($dir);
$data = [];
foreach ($files as $key => $filename) {
    if ($filename !== "." and $filename !== "..") {
        $file  = $dir.$filename;
        if (preg_match("/([a-zA-Z0-9\s_\\.\-\(\):])+.js$/i", $filename)) {
            
            $ouput = exec("node $file");
           
        }
        if (preg_match("/([a-zA-Z0-9\s_\\.\-\(\):])+.php$/i", $filename)) {
            $ouput = exec("php $file");  
    
        }
        if (preg_match("/([a-zA-Z0-9\s_\\.\-\(\):])+.py$/i", $filename)) {
            $ouput = json_encode(exec("py $file"));    
        }
        $ouput = json_decode($ouput);
        $pattern = "/Hello\sWorld,\sthis\sis\s\w+(?:\s\w+)*\swith\sHNGi7\sID\sHNG-[0-9]{5}\susing\s\w+\sfor\sstage\s2\stask/i";
        $data[$key-2]['file'] = $filename;
        $data[$key-2]['name'] = $ouput->name;
        $data[$key-2]['message'] = $ouput->message;
        $data[$key-2]['email'] = $ouput->email;
        $data[$key-2]['hng_id'] = $ouput->id;
        $data[$key-2]['status'] = (preg_match($pattern, $ouput->message)) ? "Passed" : "Failed";
        
        
    }
}
$passes = 0;
$fails = 0;
foreach ($data as $key => $value) {
    if ($value['status'] == "Passed") {
        $passes += 1;
    }else{
        $fails += 1;
    }
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Team Fury Task Tests</title>
    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
</head>
<body>
    <?php 
    if ($_SERVER["QUERY_STRING"] == "json") {
        echo json_encode($data);
    }else{?>
    
    <nav class="navbar navbar-default">
    <div>HNGi7 Team Furry</div>
    <div class="navbar">
        <div>Lead: @godstime</div>
        <div>Backend: @lead</div>
        <div>DevOps: @lead</div>
    </div>
    </nav>
    <div  class="container">
        <div class="top">
            <div>Submitted: <?php echo count($data) ?></div>
            <div>Passed: <?php echo $passes  ?></div>
            <div>Failed: <?php echo $fails  ?></div>
        </div>
        <table>
            <thead>
                <th>#</th>
                <th>Name</th>
                <th>Message</th>
                <th>Status</th>
            </thead>
            <tbody>
                <?php for ($i=0; $i < count($data); $i++) { ?>
                    <tr>
                        <td><?php echo $i ?></td>
                        <td><?php echo $data[$i]['name'] ?></td>
                        <td><?php echo $data[$i]['message'] ?></td>
                        <td><?php echo $data[$i]['status'] ?></td>
                    </tr>
                <?php } ?>

            </tbody>
        </table>
    </div>
                <?php } ?>
</body>
</html>
```

Review if and check with other files.

**Comment by piouson** [comment]
@Tijatech wow you've spent good time on this, thank you!!

Can you please move this to #22 where @dave-ok is already working on a solution.
You both and others can brainstorm on there..

**Comment by sheuabdulazeez** [comment]
Ok @piouson

**Comment by codessage** [comment]
Splendid job @Tijatech

**Comment by Arch997** [comment]
Hey guys, on the regex. I would suggest we add a fail-safe that considers the possibility of someone having their HNG ID in brackets. I'll give an example in python. I'm sure PHP guys can replicate it:

pattern = r"Hello world\S? this is \w+/S? with HNGi7 ID \W?\S?\w+-\d+\W?\S? using (Python|Javascript||PHP|Java) for Stage 2 task"

The idea is that I'm writing my ID in a bracket after the  "with HNGi7ID". The patterns I'm seeing will not match it. Please respond to this if you see it. My script is like that and I'm not ready to pull it again😩

**Comment by piouson** [comment]
Hey @Arch997 thanks for working on this, can you please share your PR number in #22 and add your idea there as well.

I think the [**Task Specification**](https://hngi7.slack.com/archives/C013K32KMRQ/p1591112636085500) was clear enough, there shouldn't be brackets around IDs, however, some might do this, so at the very least, we might want to consider this..

Discuss with @dave-ok in #22

**Comment by Arch997** [comment]
Well we should incorporate it. The text is intrinsically still valid.

**Comment by piouson** [comment]
FYI @ismailMuhammed2019 has demo'd a [**Live Site**](http://54.236.54.185/team-fury-1/) of the last commit from @dave-ok 🥇

**Comment by Adiomojeed** [comment]
@dave-ok can you add my script to the files you are testing so I can know my status. It is in my PR, where you copied the FE UI codes
