### ISSUE TITLE
Email Regex in Output

### ISSUE THREAD

**Issue by ghost** [jgodstime/team-fury-1#104]
The parser.php $regex includes the email and mark has instructed we leave our email out of the output....it should only be one of the variables in our script.....
Can this issue be addressed?
![Screenshot_20200603-181303](https://user-images.githubusercontent.com/56497524/83746432-fbcaed80-a656-11ea-8559-f532007a4230.png)

**Comment by DerKaiser7** [comment]
Write your script like that with the email, the parser.php will handle the rest.

**Comment by samueluchendu** [comment]
Great work guys, well done
 I think it would be ok if we add a  `pre` tag to format the Json output nicely on the browser when the index.php?json is requested.
just my little suggestion
