### ISSUE TITLE
Remove email from regex

### ISSUE THREAD

**Issue by mocktarissa** [jgodstime/team-fury-1#302]
The assignment doesn't require us to output our email. And as it stands those who will not provide it will get a fail.

**Comment by piouson** [comment]
This is similar to #104 

Instead of removing email all together, we can make it optional so scripts pass with or without email:

Change

```php
$regex = /Hello World, this is ([a-zA-Z\s]+) with HNGi7 ID (HNG-\d{5}) and email ([_a-z0-9-]+[\.[_a-z0-9-]+]*@[a-z0-9-]+[\.[a-z0-9-]+]*.[a-z]{2,3}) using ([\w\s]+) for stage 2 task/i
```

To

```php
$regex = /Hello World, this is ([a-zA-Z\s]+) with HNGi7 ID (HNG-\d{5})( and email ([_a-z0-9-]+[\.[_a-z0-9-]+]*@[a-z0-9-]+[\.[a-z0-9-]+]*.[a-z]{2,3}))? using ([\w\s]+) for stage 2 task/
```

**Comment by ghost** [comment]
@piouson exactly....thats correct

**Comment by piouson** [comment]
@mocktarissa or @Fortunate245 do you wish to submit a pull request for this, just change the regex that's all..

**Comment by ghost** [comment]
@piouson  is it advisable to change or tamper with the regex? or should be left like that

**Comment by piouson** [comment]
Many have changed to the email but nothing wrong with submitting a PR, its either merged or not innit

**Comment by ghost** [comment]
@piouson  Okay...... Please my Pr is still pending ?
