### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by mocktarissa** [jgodstime/team-fury-1#475]
**Ensure Language in script and file type are the same**
If the intern chooses Python as his main language for stage 2 then he should use a python file etc..

**Comment by piouson** [comment]
Very good @mocktarissa 
Lemme review the current conditional logic and then make my own suggestion to the code here

**Comment by fridaychukwuamaka** [comment]
PlS, on the HTML page, can It be changed from undefined to N/A
