### ISSUE TITLE
Creating Server to run script and also to watchout for new commits

### ISSUE THREAD

**Issue by IsmailMuhammed2019** [jgodstime/team-fury-1#52]
I have created a server that is currently running on aws and it runs the scripts for php, python, and also nodejs...now I would like to make it watch for each commit that is been done so as to have a straight and effect server for the display of output for each commit.

Thank you.

**Comment by simply-alliv** [comment]
Hey, are you talking about continuous deployment in which each commit would trigger a new build of the server and deploy that new build to aws?

If so, I can work on it with you.
