### ISSUE TITLE
Merging PRs of Scripts Team

### ISSUE THREAD

**Issue by simply-alliv** [jgodstime/team-fury-1#555]
This issue is responsible for ensuring that all open PRs for scripts are closed before the deadline. The review team should coordinate with us to increase our productivity. Will communicate with them on that.

- @peacepac Please deal with the PRs from page 1
- @johnsani Please deal with the PRs from page 2
- @maroafenogho Please deal with the PRs from page 3
- @Francisop Please deal with the PRs from page 4

## Update

We will now be reviewing and merging the PRs.

- Add a label "under review" when you start working on a PR.
- Check the base branch is dev if not, edit the title and change to dev branch before merging..
- Do not merge too many files
- If you find errors, please add to the [Invalid Scripts](https://docs.google.com/document/d/1Eoz0AP-QaQr5i-sVlXXsG7RkU2b2fPaUzOpUOoMVp9k/edit?usp=sharing) file.

**Comment by maroafenogho** [comment]
Ok. Great

**Comment by johnsani** [comment]
Alright

**Comment by Peacepac** [comment]
cool

**Comment by Francisop** [comment]
great

**Comment by johnsani** [comment]
> This issue is responsible for ensuring that all open PRs for scripts are closed before the deadline. The review team should coordinate with us to increase our productivity. Will communicate with them on that.
> 
> * @Peacepac Please deal with the PRs from page 1
> * @johnsani Please deal with the PRs from page 2

So we can go ahead and merge PRs that are okay?

**Comment by maroafenogho** [comment]
Noted

**Comment by simply-alliv** [comment]
@johnsani Yes, the reviewers will leave a label "Able to merge" on all PRs that are okay to be merged.

**Comment by johnsani** [comment]
Noted

**Comment by simply-alliv** [comment]
Let's just wait a bit for the review team to set up and start adding those labels then we can start getting to work

**Comment by johnsani** [comment]
Seems we don't have access to merge yet

**Comment by simply-alliv** [comment]
> Seems we don't have access to merge yet

@piouson should handle this.

**Comment by johnsani** [comment]
okay, I'm waiting.

> > Seems we don't have access to merge yet
> 
> @piouson should handle this.

**Comment by Rubylena** [comment]
go ahead with you reviews. am here to merge or close merge.

**Comment by simply-alliv** [comment]
How is everyone doing so far? Any possible issues that any would like to address or discuss?
