### ISSUE TITLE
Python Scripts not working on my xampp.

### ISSUE THREAD

**Issue by maroafenogho** [jgodstime/team-fury-1#567]
Someone please help me look at this code:

https://github.com/hng-teamfury/team-fury-1/pull/454/commits/6c70e10bb1325b219919b058149079debcda48d7

**Comment by simply-alliv** [comment]
Did you end up getting this sorted?

**Comment by maroafenogho** [comment]
No. I just started using the gitpod for python scripts

**Comment by simply-alliv** [comment]
Well, I had a similar issue on my local server. Changing the cli command from python to py in the parser fixed the problem.

**Comment by maroafenogho** [comment]
Ok.
Thanks

**Comment by simply-alliv** [comment]
Just make sure that if you do make commits, you revert that code back to the original.

I'll close this issue.
