### ISSUE TITLE
israel

### ISSUE THREAD

**Issue by adeoyebrass** [jgodstime/team-fury-1#583]
var text="hello world,Am ";
var fullname="Israel ";
var word="from ";
var company="HNGi7 ";
var id="HNG-04195 ";
var text1="using ";
var language="javascript language ";
var stage="for stage 2 task email is,";
var email="adeoyefemi3@gmail.com";
console.log(text+fullname+word+company+id+text1+language+stage+email);

**Comment by simply-alliv** [comment]
I'm not exactly sure what this is for but I will close this issue with a suggestion that I hope helps.

If this is part of a script that you would like to commit, see the [README](https://github.com/hng-teamfury/team-fury-1/blob/dev/README.md) file for instructions.
