### ISSUE TITLE
Implement frontend ui

### ISSUE THREAD

**Issue by piouson** [jgodstime/team-fury-1#61]
Many of us are separately working on a UI version, this issue is to help merge our efforts to go with the backend in #22 

Please review work so far and discuss with @Adiomojeed in #2 for all frontend ideas.

You can mention your PRs here if any or move all discussions to #2 

Thank you!

**Comment by Adiomojeed** [comment]
@piouson  Please who is in charge of merging PRs? I have my PR here https://github.com/jgodstime/team-fury-1/pull/2 since yesterday and it is not being merged. What is going wrong?

**Comment by piouson** [comment]
@Adiomojeed I've seen this problem too, PRs are not even getting responses or feedbacks, we need more maintainers!
I've tried to ask if I can be of help but the team leaders are doing what they can, it seems like they're swamped, so strange they not seeking more help..
You too should ask how you can help. But next stage we must add manpower to the lead team for better management..
