### ISSUE TITLE
Live server edit

### ISSUE THREAD

**Issue by maroafenogho** [jgodstime/team-fury-1#610]
The names of the old team leads is what shows on our live server. Someone please look into it and change it.

**Comment by olabode-dev** [comment]
You need to edit the html file, I think one of the leads should do it, so someone wont mistakenly tamper with wrong code

**Comment by Arch997** [comment]
Is anyone working on this yet?

**Comment by simply-alliv** [comment]
@Arch997 Seemingly not. You can make the changes and then make a PR.

Just make sure that you get the correct names of the relevant positions.

**Comment by Arch997** [comment]
@simply-alliv I don't have their names

**Comment by hng-teamfury** [comment]
Done
