### ISSUE TITLE
Ideas for the next tasks

### ISSUE THREAD

**Issue by piouson** [jgodstime/team-fury-1#824]
# Stage 2
![image](https://user-images.githubusercontent.com/17856665/83970719-17d8c400-a8cf-11ea-8961-7a6d465fd77e.png)
[**Slack Link**](https://hngi7.slack.com/archives/C013K32KMRQ/p1591537264386800)

![image](https://user-images.githubusercontent.com/17856665/83970706-0394c700-a8cf-11ea-87f7-6b98d89a17e0.png)
[**Slack Link**](https://hngi7.slack.com/archives/C013K32KMRQ/p1591537295392700)

![image](https://user-images.githubusercontent.com/17856665/83970688-e65ff880-a8ce-11ea-979a-65e265b54791.png)
[**Slack Link**](https://hngi7.slack.com/archives/C013K32KMRQ/p1591537382408200 )

![image](https://user-images.githubusercontent.com/17856665/83970826-c11fba00-a8cf-11ea-9144-67999bac1059.png)
[**Slack Link**](https://hngi7.slack.com/archives/C013K32KMRQ/p1591538097474600)

##  Designers
![image](https://user-images.githubusercontent.com/17856665/83970742-38a11980-a8cf-11ea-959d-991b74bca486.png)
[**Slack Link**](https://hngi7.slack.com/archives/C013K32KMRQ/p1591537539422700)

## Mobile
![image](https://user-images.githubusercontent.com/17856665/83970785-80c03c00-a8cf-11ea-9e97-f8edfb3fcfab.png)
[**Slack Link**](https://hngi7.slack.com/archives/C013K32KMRQ/p1591537761438900)

## Frontend
![image](https://user-images.githubusercontent.com/17856665/83970797-92094880-a8cf-11ea-99c9-e5cb4202ac8b.png)
[**Slack Link**](https://hngi7.slack.com/archives/C013K32KMRQ/p1591537859445300)

## Backend
![image](https://user-images.githubusercontent.com/17856665/83970809-a3eaeb80-a8cf-11ea-8831-e1c52484bd54.png)
[**Slack Link**](https://hngi7.slack.com/archives/C013K32KMRQ/p1591538068471200)

**Comment by Alphajeez96** [comment]
We need to find a way to secure and safeguard the designers we have while sourcing for others @piouson

**Comment by Alphajeez96** [comment]
Away from that how do we manage each design? Different repositories? One repo with many branches?

**Comment by piouson** [comment]
please dont comment, need to move this to new repo

**Comment by piouson** [comment]
Use new repo https://github.com/hng-teamfury/stage2/issues/1
